In [1]:
import pandas as pd
import numpy as np
import re
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('data_400_5000',sep = ',', index_col= 'Unnamed: 0')
data.head(3)

,operation,property_type,place_name,place_with_parent_names,country_name,state_name,geonames_id,lat-lon,lat,lon,...,surface_covered_in_m2,price_usd_per_m2,price_per_m2,floor,rooms,expenses,properati_url,description,title,image_thumbnail
0,sell,PH,Mataderos,|Argentina|Capital Federal|Mataderos|,Argentina,Capital Federal,3430787.0,"-34.6618237,-58.5088387",-34.661824,-58.508839,...,40.0,1127.272727,1550.000000,NaN,NaN,NaN,http://www.properati.com.ar/15bo8_venta_ph_mat...,"2 AMBIENTES TIPO CASA PLANTA BAJA POR PASILLO,...",2 AMB TIPO CASA SIN EXPENSAS EN PB,https://thumbs4.properati.com/8/BluUYiHJLhgIIK...
2,sell,apartment,Mataderos,|Argentina|Capital Federal|Mataderos|,Argentina,Capital Federal,3430787.0,"-34.6522615,-58.5229825",-34.652262,-58.522982,...,55.0,1309.090909,1309.090909,NaN,NaN,NaN,http://www.properati.com.ar/15bod_venta_depart...,2 AMBIENTES 3ER PISO LATERAL LIVING COMEDOR AM...,2 AMB 3ER PISO CON ASCENSOR APTO CREDITO,https://thumbs4.properati.com/5/SXKr34F_IwG3W_...
4,sell,apartment,Centro,|Argentina|Buenos Aires Costa Atlántica|Mar de...,Argentina,Buenos Aires Costa Atlántica,3435548.0,"-38.0026256,-57.5494468",-38.002626,-57.549447,...,35.0,1828.571429,1828.571429,NaN,NaN,NaN,http://www.properati.com.ar/15bok_venta_depart...,DEPARTAMENTO CON FANTÁSTICA ILUMINACIÓN NATURA...,DEPTO 2 AMB AL CONTRAFRENTE ZONA CENTRO/PLAZA ...,https://thumbs4.properati.com/5/xrRqlNcSI_vs-f...

In [73]:
# selección de barrios con similares características
list_places_name = ['Nuñez','Belgrano','Palermo']
mask_places  = data['place_name'].apply(lambda x : x in list_places_name)
data = data.loc[mask_places,:]
data.head()

,operation,property_type,place_name,place_with_parent_names,country_name,state_name,geonames_id,lat-lon,lat,lon,...,price_usd_per_m2,price_per_m2,floor,rooms,expenses,properati_url,description,title,image_thumbnail,amenities
7,sell,apartment,Belgrano,|Argentina|Capital Federal|Belgrano|,Argentina,Capital Federal,3436077.0,"-34.5598729,-58.443362",-34.559873,-58.443362,...,3066.666667,3450.000000,NaN,NaN,NaN,http://www.properati.com.ar/15bot_venta_depart...,EXCELENTE MONOAMBIENTE A ESTRENAR AMPLIO SUPER...,JOSE HERNANDEZ 1400 MONOAMBIENTE ESTRENAR CAT...,https://thumbs4.properati.com/1/IHxARynlr8sPEW...,0
8,sell,apartment,Belgrano,|Argentina|Capital Federal|Belgrano|,Argentina,Capital Federal,3436077.0,"-34.5598729,-58.443362",-34.559873,-58.443362,...,3000.000000,3250.000000,NaN,NaN,NaN,http://www.properati.com.ar/15bou_venta_depart...,EXCELENTE DOS AMBIENTES ESTRENAR AMPLIO SUPER...,"JOSE HERNANDEZ 1400 DOS AMBIENTES ESTRENAR ,...",https://thumbs4.properati.com/2/J3zOjgaFHrkvnv...,0
19,sell,apartment,Palermo,|Argentina|Capital Federal|Palermo|,Argentina,Capital Federal,3430234.0,"-34.580503566,-58.4058744847",-34.580504,-58.405874,...,3365.384615,3645.833333,NaN,3.0,NaN,http://www.properati.com.ar/15bq8_venta_depart...,Excelente semipiso al contra frente en Bulnes ...,"Bulnes y Libertador: espectacular pulmón, con ...",https://thumbs4.properati.com/8/1y9fKHLee-aQQj...,1
21,sell,apartment,Palermo,|Argentina|Capital Federal|Palermo|,Argentina,Capital Federal,3430234.0,"-34.590926,-58.4116653",-34.590926,-58.411665,...,2292.372881,3705.479452,NaN,4.0,NaN,http://www.properati.com.ar/15bqd_venta_depart...,"EXCELENTE ZONA, MULTIPLES MEDIOS DE TRANSPORTE...",Departamento de 4 ambientes en Venta en Palermo,https://thumbs4.properati.com/0/P6wPIXB1wJFLVU...,0
60,sell,apartment,Nuñez,|Argentina|Capital Federal|Nuñez|,Argentina,Capital Federal,3430348.0,"-34.5535776,-58.4555114",-34.553578,-58.455511,...,3460.000000,3460.000000,NaN,2.0,NaN,http://www.properati.com.ar/15bvo_venta_depart...,ESPECTACULAR DEPARTAMENTO DE 2 AMBIENTES CON C...,"VENTA 2 AMB CON COCH, PISCINA PARA INVERSION...",https://thumbs4.properati.com/0/HIvLnvwib7BBZ5...,0

In [74]:
data.isnull().sum()

operation                        0
property_type                    0
place_name                       0
place_with_parent_names          0
country_name                     0
state_name                       0
geonames_id                      0
lat-lon                       1200
lat                           1200
lon                           1200
price                            0
currency                         0
price_aprox_local_currency       0
price_aprox_usd                  0
surface_total_in_m2              0
surface_covered_in_m2          264
price_usd_per_m2                 0
price_per_m2                   264
floor                         4220
rooms                         2754
expenses                      2894
properati_url                    0
description                      0
title                            0
image_thumbnail                 32
amenities                        0
dtype: int64

In [75]:
data.shape

(4431, 26)

In [76]:
data['place_name'].value_counts()

Belgrano    2061
Palermo     1859
Nuñez        511
Name: place_name, dtype: int64

A analizar:
rooms - cantidad de ambientes
amenities
tipo de propiedad
barrio

In [91]:
# data.groupby(['place_name','property_type'])['operation'].count()
data.pivot_table(index= 'place_name', columns= 'property_type', aggfunc= {'operation': 'count'})

              operation
property_type        PH apartment house store
place_name
Belgrano             34      1913    80    34
Nuñez                18       450    26    17
Palermo              78      1691    36    54

In [78]:
data_apparment = data.loc[data.property_type == 'apartment']
data_apparment.head()

,operation,property_type,place_name,place_with_parent_names,country_name,state_name,geonames_id,lat-lon,lat,lon,...,price_usd_per_m2,price_per_m2,floor,rooms,expenses,properati_url,description,title,image_thumbnail,amenities
7,sell,apartment,Belgrano,|Argentina|Capital Federal|Belgrano|,Argentina,Capital Federal,3436077.0,"-34.5598729,-58.443362",-34.559873,-58.443362,...,3066.666667,3450.000000,NaN,NaN,NaN,http://www.properati.com.ar/15bot_venta_depart...,EXCELENTE MONOAMBIENTE A ESTRENAR AMPLIO SUPER...,JOSE HERNANDEZ 1400 MONOAMBIENTE ESTRENAR CAT...,https://thumbs4.properati.com/1/IHxARynlr8sPEW...,0
8,sell,apartment,Belgrano,|Argentina|Capital Federal|Belgrano|,Argentina,Capital Federal,3436077.0,"-34.5598729,-58.443362",-34.559873,-58.443362,...,3000.000000,3250.000000,NaN,NaN,NaN,http://www.properati.com.ar/15bou_venta_depart...,EXCELENTE DOS AMBIENTES ESTRENAR AMPLIO SUPER...,"JOSE HERNANDEZ 1400 DOS AMBIENTES ESTRENAR ,...",https://thumbs4.properati.com/2/J3zOjgaFHrkvnv...,0
19,sell,apartment,Palermo,|Argentina|Capital Federal|Palermo|,Argentina,Capital Federal,3430234.0,"-34.580503566,-58.4058744847",-34.580504,-58.405874,...,3365.384615,3645.833333,NaN,3.0,NaN,http://www.properati.com.ar/15bq8_venta_depart...,Excelente semipiso al contra frente en Bulnes ...,"Bulnes y Libertador: espectacular pulmón, con ...",https://thumbs4.properati.com/8/1y9fKHLee-aQQj...,1
21,sell,apartment,Palermo,|Argentina|Capital Federal|Palermo|,Argentina,Capital Federal,3430234.0,"-34.590926,-58.4116653",-34.590926,-58.411665,...,2292.372881,3705.479452,NaN,4.0,NaN,http://www.properati.com.ar/15bqd_venta_depart...,"EXCELENTE ZONA, MULTIPLES MEDIOS DE TRANSPORTE...",Departamento de 4 ambientes en Venta en Palermo,https://thumbs4.properati.com/0/P6wPIXB1wJFLVU...,0
60,sell,apartment,Nuñez,|Argentina|Capital Federal|Nuñez|,Argentina,Capital Federal,3430348.0,"-34.5535776,-58.4555114",-34.553578,-58.455511,...,3460.000000,3460.000000,NaN,2.0,NaN,http://www.properati.com.ar/15bvo_venta_depart...,ESPECTACULAR DEPARTAMENTO DE 2 AMBIENTES CON C...,"VENTA 2 AMB CON COCH, PISCINA PARA INVERSION...",https://thumbs4.properati.com/0/HIvLnvwib7BBZ5...,0

In [79]:
data_apparment.shape

(4054, 26)

In [70]:
#busqueda de amenities en dataset final

#match amenities
pattern_amenities = "balcon|balcón"#|cochera|parrilla|pileta|amoblado|lavadero|patio|terraza|jardin|jardín"
match_pattern_amenities = data_apparment.description.str.contains(pattern_amenities, regex= True)
print('Coincidencias amenities ' + str(match_pattern_amenities.sum()))
mask_match_pattern_amenities_notnull = match_pattern_amenities.notnull()

Coincidencias amenities 1614

In [52]:
#incorporación de columna 'amenities' al data final
data_apparment.loc[mask_match_pattern_amenities_notnull, "amenities"] = match_pattern_amenities[mask_match_pattern_amenities_notnull].astype(int)

c:\Users\Irma\anaconda3\envs\dhdsblend2021\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

In [ ]:

pattern_balcon = "balcón|balcon"

pattern_balcon_regex = re.compile(pattern_balcon)
address_series = data.Address
resultado_nombres = address_series.apply(lambda x: pattern_nombre_regex.search(x))
#print(type(resultado))
print(resultado_nombres)

In [ ]:
calles_match = resultado_nombres.apply(lambda x: x if x is None else x.group('nombre_calle'))
calles_match

In [56]:
description_date_series = data_apparment['description']
description_date_series

7         EXCELENTE MONOAMBIENTE A ESTRENAR AMPLIO SUPER...
8         EXCELENTE DOS AMBIENTES  ESTRENAR AMPLIO SUPER...
19        Excelente semipiso al contra frente en Bulnes ...
21        EXCELENTE ZONA, MULTIPLES MEDIOS DE TRANSPORTE...
60        ESPECTACULAR DEPARTAMENTO DE 2 AMBIENTES CON C...
                                ...
121113    Amplio 3 ambientes en pleno Palermo, a una cua...
121146    VENTA PISO CON COCHERA EN PALERMOMuy buena ubi...
121157    Torre de 16º pisos ubicado en pleno centro com...
121160    Edificio en esquina de muy buena categoría de ...
121209    Edificio en esquina de muy buena categoría de ...
Name: description, Length: 4054, dtype: object

In [62]:
amenities_pattern = "(P<balcon>(balcon|balcón))"
amenities_pattern_regex = re.compile(amenities_pattern)

data_amenities_match = description_date_series.apply(lambda x: x if x is np.NaN else amenities_pattern_regex.search(x))

mask_data_amenities_match_notnull = data_amenities_match.notnull()

data_apparment.loc[mask_data_amenities_match_notnull, "amenities_1"] = data_amenities_match[mask_data_amenities_match_notnull].apply(lambda x: x.group('balcon'))

c:\Users\Irma\anaconda3\envs\dhdsblend2021\lib\site-packages\pandas\core\indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

In [69]:
data_amenities_match

7         None
8         None
19        None
21        None
60        None
          ...
121113    None
121146    None
121157    None
121160    None
121209    None
Name: description, Length: 4054, dtype: object

In [64]:
data_apparment['amenities_1']

7         NaN
8         NaN
19        NaN
21        NaN
60        NaN
         ...
121113    NaN
121146    NaN
121157    NaN
121160    NaN
121209    NaN
Name: amenities_1, Length: 4054, dtype: object